# Generated by Django 4.2.4 on 2023-08-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
    ]
